name: Hello world workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Hello world step
              run: echo "Hello everyone!"
              shell: bash
    
    githubworkspace:
        runs-on: ubuntu-latest
        steps:
            - name: Display workspace path
              run: echo $GITHUB_WORKSPACE
              shell: bash
